### ISSUE TITLE
error while executing settle function 

### ISSUE THREAD

**Issue by K00LNERD** [algorand-devrel/coin-flipper#3]
got this error  while running the main file 

algosdk.error.AlgodHTTPError: TransactionPool.Remember: transaction IZJ4ENB3JYZAMPW6CO3YYEPW63KFCYL7RDGFS2SJA2CW5WZQ4OEA: logic eval error: logic eval error: assert failed pc=862. Details: pc=862, opcodes=load 14
callsub label26
assert
. Details: pc=598, opcodes=load 24
itxn_field ApplicationArgs
itxn_submit

nullun on discord said this about it - "Your inner transaction is failing. The application you're calling is calling another application, which is failing because a subroutine isn't returning with a positive number on the stack."

this is the whole error message 

srijanvarma@Srijans-MBP coin-flipper % "/Users/srijanvarma/Desktop/algorand coinflipper/coin-flipper/.venv/bin/python" "/Users/srijanvarma/Desktop/
algorand coinflipper/coin-flipper/contracts/main.py"
Created app at 116522355 MDOOOQQUW4ITYYCEX3IJHKJGC5BLMBYSK7F2GISABTU3I6BMNDL23RTMHY
Funded app
Opted in
Current app state:{'beacon_app_id': 110096026, 'bets_outstanding': 0, 'max_bet': 1000000, 'min_bet': 5000}
Flipping coin :crossed_fingers:
Bet placed for round: 24845129
Currently at round 24845128
Currently at round 24845129
Currently at round 24845130
Settling...
Traceback (most recent call last):
  File "/Users/srijanvarma/Desktop/algorand coinflipper/coin-flipper/.venv/lib/python3.10/site-packages/algosdk/v2client/algod.py", line 78, in algod_request
    resp = urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return [http://opener.open](https://t.co/ifmOMWHnRH)(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/srijanvarma/Desktop/algorand coinflipper/coin-flipper/.venv/lib/python3.10/site-packages/beaker/client/application_client.py", line 500, in call
    result = atc.execute(self.client, 4)
  File "/Users/srijanvarma/Desktop/algorand coinflipper/coin-flipper/.venv/lib/python3.10/site-packages/algosdk/atomic_transaction_composer.py", line 483, in execute
    self.submit(client)
  File "/Users/srijanvarma/Desktop/algorand coinflipper/coin-flipper/.venv/lib/python3.10/site-packages/algosdk/atomic_transaction_composer.py", line 450, in submit
    client.send_transactions(self.signed_txns)
  File "/Users/srijanvarma/Desktop/algorand coinflipper/coin-flipper/.venv/lib/python3.10/site-packages/algosdk/v2client/algod.py", line 330, in send_transactions
    return self.send_raw_transaction(
  File "/Users/srijanvarma/Desktop/algorand coinflipper/coin-flipper/.venv/lib/python3.10/site-packages/algosdk/v2client/algod.py", line 260, in send_raw_transaction
    return self.algod_request("POST", req, data=txn, **kwargs)["txId"]
  File "/Users/srijanvarma/Desktop/algorand coinflipper/coin-flipper/.venv/lib/python3.10/site-packages/algosdk/v2client/algod.py", line 85, in algod_request
    raise error.AlgodHTTPError(e, code)
algosdk.error.AlgodHTTPError: TransactionPool.Remember: transaction IZJ4ENB3JYZAMPW6CO3YYEPW63KFCYL7RDGFS2SJA2CW5WZQ4OEA: logic eval error: logic eval error: assert failed pc=862. Details: pc=862, opcodes=load 14
callsub label26
assert
. Details: pc=598, opcodes=load 24
itxn_field ApplicationArgs
itxn_submit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/srijanvarma/Desktop/algorand coinflipper/coin-flipper/contracts/main.py", line 96, in <module>
    demo(app_id=APP_ID)
  File "/Users/srijanvarma/Desktop/algorand coinflipper/coin-flipper/contracts/main.py", line 89, in demo
    result = app_client.call(
  File "/Users/srijanvarma/Desktop/algorand coinflipper/coin-flipper/.venv/lib/python3.10/site-packages/beaker/client/application_client.py", line 503, in call
    raise self.wrap_approval_exception(e)
beaker.client.logic_error.LogicException: <exception str() failed>
<img width="1440" alt="Screenshot 2022-10-16 at 1 42 03 PM" src="https://user-images.githubusercontent.com/43308707/196036645-5787e253-599c-46cc-bdc8-6bb76e6ef216.png">

**Comment by barnjamin** [comment]
Have you tried dryruning it? given the error:

```
logic eval error: assert failed pc=862. Details: pc=862, opcodes=load 14
callsub label26
assert
. Details: pc=598, opcodes=load 24
itxn_field ApplicationArgs
itxn_submit
```

Some condition in the contract being called is being violated, probably the limit of rounds the oracle has available. 


Try closing out of the app and run through it again or try with a different account

**Comment by sagaranand015** [comment]
hi @barnjamin , @K00LNERD 
Were you able to figure out the solution to this? 
I'm getting the same error and have tried with 2 separate accounts.

**Comment by barnjamin** [comment]
hi @sagaranand015 its failing in the c2c call to the oracle if its the exact same error, check the oracle logic to see what assert is failing, its likely to be an issue with the round either too early or too late. 

If its too late (past the history of the oracle) you'll need to opt the account out then try again

**Comment by sagaranand015** [comment]
Yes, you are right. The issue was I was calling the oracle too early, adding a few rounds before the calling resolved the issue. Thank you for the help.
